stages:
  -test
  -build

test1:
  stage: test
  script:
  - echo "test 1"

test2:
  stage: test
  script:
  - echo "test 2"
  
test3:
  stage: test
  script:
  - echo "test 3"

build:
  stage: build
  script:
  - ./build.sh
  

  

