name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test 1
        run: echo "test 1"

  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test 2
        run: echo "test 2"

  test3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test 3
        run: echo "test 3"

  build:
    runs-on: self-hosted
    needs: [test1, test2, test3] # Зависит от выполнения всех тестов
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: .github/workflows/build.sh

