name: CI Pipeline Site

on:
  push:
    branches:
      - master
      - 'release*'
  pull_request:
    branches:
      - master
      - 'release*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to web server
        run: cp -r ./html/* /var/www/html
