name: CI Pipeline site

on:

stages:
  - deploy
deploy:
  stage: deploy
  script:
    - cp -r ./html/* /var/www/html
  tags:
    - stage-shell
  only:
    refs:
      - tags
      - master
      - /release.*$/